# Generated by Django 4.1.7 on 2023-03-09 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.ForeignKey(default='000000', on_delete=django.db.models.deletion.CASCADE, to='myapp.year'),
            preserve_default=False,
        ),
    ]
